version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.1.2
    steps:
      - checkout

      - restore_cache:
          key: v1-deps-{{ checksum "composer.json" }}

      - run:
          name: install dependencies
          command: composer install

      - save_cache:
          key: v1-deps-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run: ./vendor/bin/phpunit
